#!/bin/bash
# Mihir Kalyanthaya
# Question 1
# 10/11/2024

# create main project directory
mkdir -p bioinformatics_project

# create subdirectories
mkdir -p bioinformatics_project/data
mkdir -p bioinformatics_project/scripts
mkdir -p bioinformatics_project/results

# create empty python files in scripts directory
touch bioinformatics_project/scripts/generate_fasta.py
touch bioinformatics_project/scripts/dna_operations.py
touch bioinformatics_project/scripts/find_cutsites.py

# create an empty file in results directory
touch bioinformatics_project/results/cutsite_summary.txt

# create an empty file in data directory
touch bioinformatics_project/data/random_sequence.fasta

# create README.md file in main project directory with project structure description
echo "# Exam 1 Question 1 Bioinformatics Project" > bioinformatics_project/README.md
echo "" >> bioinformatics_project/README.md
echo "Project directory structure: " >> bioinformatics_project/README.md
echo "- 'data/': Input data files." >> bioinformatics_project/README.md
echo "- 'scripts/': Python scripts for data processing." >> bioinformatics_project/README.md
echo "- 'results/': Output files from analysis." >> bioinformatics_project/README.md

chmod +x setup_project.sh

# terminal input and output
#bioinformatics_project Directory
# PS C:\Users\mihir\OneDrive\Desktop\bioinformatics_project> ls
#     Directory: C:\Users\mihir\OneDrive\Desktop\bioinformatics_project


# Mode                 LastWriteTime         Length Name
# ----                 -------------         ------ ----
# da---l        10/11/2024   1:12 PM                data
# da---l        10/11/2024   1:12 PM                results
# da---l        10/11/2024   1:12 PM                scripts
# -a---l        10/11/2024   2:10 PM            195 README.md

#SCRIPTS Directory
# PS C:\Users\mihir\OneDrive\Desktop\bioinformatics_project\scripts> ls
#     Directory: C:\Users\mihir\OneDrive\Desktop\bioinformatics_project\scripts


# Mode                 LastWriteTime         Length Name
# ----                 -------------         ------ ----
# -a---l        10/11/2024   2:10 PM              0 dna_operations.py
# -a---l        10/11/2024   2:10 PM              0 find_cutsites.py
# -a---l        10/11/2024   2:10 PM              0 generate_fasta.py

# DATA Directory
# PS C:\Users\mihir\OneDrive\Desktop\bioinformatics_project\data> ls
#     Directory: C:\Users\mihir\OneDrive\Desktop\bioinformatics_project\data


# Mode                 LastWriteTime         Length Name
# ----                 -------------         ------ ----
# -a---l        10/11/2024   4:42 PM              0 random_sequence.fasta

# RESULTS Directory
# PS C:\Users\mihir\OneDrive\Desktop\bioinformatics_project\results> ls
#     Directory: C:\Users\mihir\OneDrive\Desktop\bioinformatics_project\results


# Mode                 LastWriteTime         Length Name
# ----                 -------------         ------ ----
# -a---l        10/11/2024   2:10 PM              0 cutsite_summary.txt







