#!/bin/bash
# Mihir Kalyanthaya
# Question 3
# 10/11/2024
import sys

def complement(sequence):
    complement_map = {'A':'T', 'T':'A', 'C':'G', 'G':'C'}
    return ''.join(complement_map[base] for base in sequence.upper())

def reverse(sequence):
    return sequence[::-1]

def reverse_complement(sequence):
    return reverse(complement(sequence))

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python dna_operations.py ")
        sys.exit(1)
    input_sequence = sys.argv[1]

    print(f"Original Sequence: {input_sequence}")
    print(f"Complement: {complement(input_sequence)}")
    print(f"Reverse: {reverse(input_sequence)}")
    print(f"Reverse Complement: {reverse_complement(input_sequence)}")

# input into terminal
# PS C:\Users\mihir> python "C:\Users\mihir\OneDrive\Desktop\bioinformatics_project\scripts\dna_operations.py" CCTCAGC
# output
# Original Sequence: CCTCAGC
# Complement: GGAGTCG
# Reverse: CGACTCC
# Reverse Complement: GCTGAGG

